insert into projects (title, text_body, text_body_background, project_url, page_id) values
('Shopify Flow New Template UI', 'This project required me build a paginated GraphQL API endpoint for automation templates, using domain driven design. I followed a Test Driven Development approach with Ruby on Rails, and navigated my way through a complex codebase with many layers.', 'As part of this work I had the opportunity to receive rigorous feedback from one of our Senior API developers, which resulted in a well-refined, scalable and fully tested API endpoint. ', 'https://apps.shopify.com/flow/', 'flow-templates'),
('Freeflow Social Network', 'This project required me to build a fully responsive Social Media platform with a complex state management system. I used HTML5 and TailwindCSS with a combination of Grid and Flexbox, and React with Redux state management to securely handle the constant state updates.', 'This project originated as a Bootcamp group project of three people. We used Gatsby.js UI to implement a beautiful and responsive layout, but soon realized this was not the optimal approach for a Social Media Application. Since the completion of our 2 week project sprint, I migrated the project off of Gatsby and onto a plain React App, then rebuilt it using Redux Toolkit for optimal State Management (still in process). My next steps in this project will be to complete the rebuild with Messaging and Notifications features implemented, and complete at least 80% test coverage on the app. Once those steps are complete, I intend to make it an Open Source Project.', 'https://freeflow-network.herokuapp.com/', 'freeflow'),
('Sovereign Birth Business Website', 'This business website required me to implement a secure admin login using Firebase for content management privileges with both front end and back end authentication and authorization. I used a React Front End with both react hooks and custom hooks (useVisualMode) nd an Express Back End, Postgresql persistent data, and Tailwind CSS.', 'This project was a great experience for me to learn more about JWT authentication and Authorization. I intend to use what I have learned to implement a more secure login with secure routes for users on the Freeflow Network. My next steps for this application is to create more Content Management accessibility for the Admin user, implement a booking calendar, and create a store with the users able to Add to Cart and checkout with Stripe.', 'https://sovereign-birth.netlify.app/', 'sovereign-birth'),
('Interview Scheduler App', 'This project was my first full introduction to building a full-stack application using React and Express. I used Storybook, Jest and Cypress testing to provide over 80% test coverage in a functional component app. The application is also hooked up to a websocket for real-time updates, and was my first experience to using a reducer.', 'This project gave me a great head start for some more advanced techniques with state management using a reducer, and the real-time update ability with websocket. The introduction to reducer was a very good prelude for me to jump into Redux as well as using context for login authentication with Freeflow.', 'https://interview-scheduler-mj.netlify.app/', 'scheduler'),
('Yogi Mathius Personal Blog', 'This project required me to build a fully responsive business website, experimenting with more advanced CSS (parallax, hover glow effects, transitions) to deepen my front-end knowledge. ', 'Looking back on this project now, I have a lot of good ideas on how I can improve the layout and style, and improve the load time of the project in general. I would love to convert this to a React project, however it is not a top priority now. This was my first encounter with using Javascript for a carousel slider, and after having a fair amount of experience using sliders I have to say I am quite pleased with the results.', 'https://yogimathius.netlify.app/', 'yogi-mathius'),
('Johnson Landscaping Website', 'This project was my first website, which had the privilege of being my personal business website from my previous profession. I used HTML5 along with CSS flexbox to build a fully responsive website, along with a PHP script for contacting my business.', 'This project can also use some revamping, but for the limited skill that I had at the time I believe the theme of it is quite nice. Looking back on it now, I intend to adjust the layout for better conformity.', 'https://johnsonlandscaping.netlify.app/index.html', 'johnson-landscaping');

insert into projectImages (project_id, image_url) values
(1, 'https://raw.githubusercontent.com/yogimathius/portfolio-fs/main/src/client/src/assets/images/new_template_ui.png'),
(2, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/freeflow.png'),
(3, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/sovereign-birth.png'),
(4, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/scheduler.png'),
(5, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/yogimathius.png'),
(6, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/johnsonlandscaping.jpeg');

insert into previewImages (project_id, image_url) values
(2, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/freeflow/screencapture-freeflow-network-netlify-app-2021-04-29-13_22_35.png'),
(3, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/sovereignbirth/screencapture-sovereign-birth-netlify-app-home-2021-04-29-13_20_42.png'),
(5, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/yogimathius/ympreviewone.png'),
(6, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/johnsonlandscaping/jlpreviewone.png'),
(6, 'https://raw.githubusercontent.com/yogimathius/portfolio2.0/master/src/assets/images/portfolio/johnsonlandscaping/screencapture-johnsonlandscaping-netlify-app-about-html-2021-04-29-13_28_05.png');